package edu.liberty.andrewwerner.iplverification.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.liberty.andrewwerner.iplverification.model.IPlayer;
import edu.liberty.andrewwerner.iplverification.model.ITeam;
import edu.liberty.andrewwerner.iplverification.model.VerificationStatus;
import edu.liberty.andrewwerner.iplverification.presenter.IPresenter;
import edu.liberty.andrewwerner.iplverification.presenter.ITeamPresenter;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.ArrayList;
import java.util.Locale;

/**
 * Class TeamView
 * Generates and maintains the GUI for the team page.
 *
 * @author Andrew Werner
 */
public final class TeamView implements ITeamView {
    private JPanel contentPanel;
    private JLabel teamName;
    private JScrollPane resultsPanel;
    private JLabel teamURL;
    private JButton goToSearchButton;
    private JButton goToEventButton;
    private JLabel eventName;
    private JComboBox<VerificationStatus> verifStatusDropdown;
    private JTextArea verificationNotes;
    private JButton saveVerificationChangesButton;
    private JLabel verificationUpdateLabel;


    private final IWidgetFactory factory;
    private ITeamPresenter presenter;
    private ITeam team;
    private URLHandler urlHandler;

    /**
     * Creates an object of class TeamView
     * @param factory the widget factory to use for making widgets.
     */
    public TeamView(IWidgetFactory factory) {
        this.factory = factory;

        // One-time loads
        for (VerificationStatus status : VerificationStatus.values()) {
            this.verifStatusDropdown.addItem(status);
        }

        // Event listeners
        this.goToSearchButton.addActionListener(e -> this.presenter.changeView(IPresenter.PID.Search));
        this.goToEventButton.addActionListener(e -> this.presenter.changeView(IPresenter.PID.Event, this.team.getEvent()));
        this.saveVerificationChangesButton.addActionListener(e -> {
            VerificationStatus newStatus = this.verifStatusDropdown.getItemAt(this.verifStatusDropdown.getSelectedIndex());
            String newNote = this.verificationNotes.getText();
            if (this.team.getVerificationStatus() == newStatus && this.team.getVerificationNote().equals(newNote)) {
                this.verificationUpdateLabel.setText("No changes to save.");
                return;
            }

            this.saveVerificationChangesButton.setEnabled(false);
            this.verificationUpdateLabel.setText("Saving changes...");

            String result = this.presenter.updateVerification(this.team, newStatus, newNote);

            this.verificationUpdateLabel.setText(result);
            this.saveVerificationChangesButton.setEnabled(true);
        });
    }

    @Override
    public void setPresenter(ITeamPresenter presenter) {
        if (this.presenter != null) {
            throw new IllegalStateException("Team Presenter already set!");
        }

        this.presenter = presenter;
    }

    @Override
    public void updateView(ITeam team, ArrayList<IPlayer> players) {
        this.team = team;
        this.teamName.setText(team.getName());
        this.eventName.setText("Event: " + team.getEvent().getName());
        if (this.urlHandler == null) {
            this.urlHandler = new URLHandler(this.teamURL, this.team.getBracketSiteURL());
        } else {
            this.urlHandler.updateLabel(this.team.getBracketSiteURL());
        }

        this.verifStatusDropdown.setSelectedItem(this.team.getVerificationStatus());
        this.verificationNotes.setText(this.team.getVerificationNote());
        this.verificationUpdateLabel.setText("");

        JPanel wrapper = this.factory.buildWidgets(this.presenter, players, false);
        this.resultsPanel.setViewportView(wrapper);
        this.resultsPanel.getVerticalScrollBar().setUnitIncrement(10);
    }

    @Override
    public JPanel getContentPanel() {
        return this.contentPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(11, 2, new Insets(10, 10, 10, 10), -1, -1));
        teamName = new JLabel();
        Font teamNameFont = this.$$$getFont$$$(null, Font.BOLD, 16, teamName.getFont());
        if (teamNameFont != null) teamName.setFont(teamNameFont);
        teamName.setText("[Team Name]");
        contentPanel.add(teamName, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        resultsPanel = new JScrollPane();
        contentPanel.add(resultsPanel, new GridConstraints(10, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        resultsPanel.setViewportView(panel1);
        final JLabel label1 = new JLabel();
        label1.setText("Loading, Please Wait...");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        teamURL = new JLabel();
        teamURL.setText("[Team URL]");
        contentPanel.add(teamURL, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        goToSearchButton = new JButton();
        goToSearchButton.setText("Back to Main Menu");
        contentPanel.add(goToSearchButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        eventName = new JLabel();
        eventName.setText("[Event Name]");
        contentPanel.add(eventName, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        goToEventButton = new JButton();
        goToEventButton.setText("Back to Event");
        contentPanel.add(goToEventButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator1 = new JSeparator();
        contentPanel.add(separator1, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Eligibility: ");
        contentPanel.add(label2, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        verifStatusDropdown = new JComboBox();
        contentPanel.add(verifStatusDropdown, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Verification Notes:");
        contentPanel.add(label3, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        verificationNotes = new JTextArea();
        verificationNotes.setLineWrap(true);
        contentPanel.add(verificationNotes, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        saveVerificationChangesButton = new JButton();
        saveVerificationChangesButton.setText("Save Verification Changes");
        contentPanel.add(saveVerificationChangesButton, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        verificationUpdateLabel = new JLabel();
        verificationUpdateLabel.setText("");
        contentPanel.add(verificationUpdateLabel, new GridConstraints(7, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Team Verification Status");
        contentPanel.add(label4, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Team Roster");
        contentPanel.add(label5, new GridConstraints(9, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JSeparator separator2 = new JSeparator();
        contentPanel.add(separator2, new GridConstraints(8, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

}
